### PR TITLE
New Entities for Chemistry and Virtual Circuits

### PR DESCRIPTION
**Pull request by rstrouse**
* Added Chem Controller index values
* Added Chem Controller Setpoints
* Added Virtual Circuit state sensors
* Hardened entity maps so incomplete data will not cause entities to go missing

### CODE REVIEW

**Comment by rstrouse** [comment]
I added more entities for virtual circuits and those that were missing from the Chem Controller functions.  Users may now control IntelliChem and REM Chem completely from within Home Assistant.  I also hardened places where the keys for the particular device may not yet exist in njsPC so users do not experience missing entities in Home Assistant.

**Comment by rstrouse** [comment]
The only outstanding items that could be added are if the user has a Chem Doser (like IntelliPh but actually automated).  We should also probably disable the superchlor function if the body isn't running.  Finally, I am still stewing around how the schedules should appear. I don't really know how important it is to be able to change them but it should probably show when a schedule is running and how much time a scheduled feature has left.

**Comment by Crewski** [comment]
Yeah, I'm not sure how to tackle schedules as well.  The simplest form would just be a binary sensor saying if it was active or not (no countdown involved).  Ideally, for me, I'd love the ability to use a switch to enable/disable a schedule to stop it from firing.

Thanks for helping out so much on this and taking it further than I ever could!

**Comment by rstrouse** [comment]
Just glad I could help.  I have been thinking about adding some schedule functions to njsPC.  I keep waffling between creating a scheduling engine and simply adding and deleting schedules on demand from a list of active and inactive schedules.  The part that makes it goofy is the way EasyTouch handles them.  Some models only have 4 schedules so the ids would have to rotate and not remain unique.

**Pull request merged**
