### PR TITLE
Changes to device based objects

### PR DESCRIPTION
**Pull request by rstrouse**
Added chemistry controllers
Added filter devices
Added control panel
Added support for ss pumps
Added body devices

### CODE REVIEW

**Comment by Crewski** [comment]
Everything seemed to work out for the most part (after I finally figured out how to update my dev container to python 3.10).  I did come across a few KeyErrors that need to be fixed.  My main system is down for the winter and my "tester" is just the program without any actual equipment hooked up, so maybe that is the issue.

- Add checks for "pressure" and "cleanPercentage" for filters:
```
    for pool_filter in config["filters"]:
        if "pressure" in pool_filter:
            new_devices.append(
                FilterPressureSensor(coordinator=coordinator, pool_filter=pool_filter)
            )
        if "cleanPercentage" in pool_filter:
            new_devices.append(
                FilterCleanSensor(coordinator=coordinator, pool_filter=pool_filter)
            )
```
- In the init for BodyHeater set coolSetpoint to null then update it if available:
```
        self.cool_setpoint = None
        if "coolSetpoint" in body:
            self.cool_setpoint = body["coolSetpoint"]
```

**Comment by rstrouse** [comment]
I went through each of the objects to ensure it checks for the existence of any key that we expect to extract data from.  Sometimes the equipment item may not have yet reported so it is likely that some of the state data may not yet be obtained.   I am also in discussions with @tagyoureit to finalize some icons to be submitted to brands.  Here are some of the ideas we are kicking around.

Icons:

icon2
icon1

Logos:

logo2x
logo

**Comment by Crewski** [comment]
One last update I think and then I'll get this merged.  For the BodyCircuitSwitch, no event is definite so it isn't responding to changes.  Simple fix thought, just make the `self._event = "circuit"` in the init.

**Comment by rstrouse** [comment]
I think I was going to process both potential events there but there really is no need until we handle delays.  That is a much bigger subject as one would also want to be able to cancel delays.  I made the change as you suggested until I get ambition to support the delays.

**Pull request merged**
